# The GIFs userland/giftest.c decodes, made by Windows' own encoder (GDI+)
# rather than by anything in this project: a decoder checked against its
# own encoder agrees with itself and proves nothing (tools/genpng.py makes
# the PNGs the same way with the host's zlib). Writes userland/gifdata.h.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools/gengif.ps1
#
# Four pictures, each for something that can go wrong:
#   small   5x4, a colour per pixel from a table of 16: the table and the rows
#   noisy   160x120 of pseudo-random indices from 256: codes past 9 bits and
#           the table filling up and being cleared
#   holes   the small one with index 3 said to be transparent, the block
#           that says so spliced in before the picture
#   laced   24x16 with its rows written in the four passes and the image
#           marked interlaced, so decoding puts them back in order
Add-Type -AssemblyName System.Drawing
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)

function Make-Gif([int]$w, [int]$h, [scriptblock]$index, [int[]]$rowOrder) {
    $bmp = New-Object System.Drawing.Bitmap($w, $h, [System.Drawing.Imaging.PixelFormat]::Format8bppIndexed)
    $pal = $bmp.Palette
    for ($i = 0; $i -lt 256; $i++) {
        $r = ($i * 37) % 256; $g = ($i * 91) % 256; $b = ($i * 53 + 17) % 256
        $pal.Entries[$i] = [System.Drawing.Color]::FromArgb(255, $r, $g, $b)
    }
    $bmp.Palette = $pal
    $rect = New-Object System.Drawing.Rectangle(0, 0, $w, $h)
    $data = $bmp.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::WriteOnly, $bmp.PixelFormat)
    $bytes = New-Object byte[] ($data.Stride * $h)
    for ($y = 0; $y -lt $h; $y++) {
        $src = if ($rowOrder) { $rowOrder[$y] } else { $y }
        for ($x = 0; $x -lt $w; $x++) { $bytes[$y * $data.Stride + $x] = [byte](& $index $x $src) }
    }
    [System.Runtime.InteropServices.Marshal]::Copy($bytes, 0, $data.Scan0, $bytes.Length)
    $bmp.UnlockBits($data)
    $ms = New-Object System.IO.MemoryStream
    $bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Gif)
    $bmp.Dispose()
    return ,$ms.ToArray()
}

function Find-Image([byte[]]$g) {
    # The offset of the image descriptor: past the header, the table and
    # any extensions.
    $at = 13
    if ($g[10] -band 0x80) { $at += 3 * (2 -shl ($g[10] -band 7)) }
    while ($g[$at] -eq 0x21) {
        $at += 2
        while ($g[$at] -ne 0) { $at += $g[$at] + 1 }
        $at++
    }
    return $at
}

$small = Make-Gif 5 4 { param($x, $y) ($y * 5 + $x) % 16 } $null
$noisy = Make-Gif 160 120 { param($x, $y) (($x * 7919 + $y * 104729 + $x * $y * 31) -band 0xFF) } $null

# holes: a graphic control block saying index 3 shows through, put in front
# of the image descriptor.
$at = Find-Image $small
$gce = [byte[]](0x21, 0xF9, 4, 1, 0, 0, 3, 0)
$holes = [byte[]]($small[0..($at - 1)] + $gce + $small[$at..($small.Length - 1)])

# laced: stored row i is the picture's row order[i], order being the passes.
$order = @()
foreach ($p in @(@(0, 8), @(4, 8), @(2, 4), @(1, 2))) {
    for ($y = $p[0]; $y -lt 16; $y += $p[1]) { $order += $y }
}
$laced = Make-Gif 24 16 { param($x, $y) ($y * 3 + $x) % 64 } $order
$at = Find-Image $laced
$laced[$at + 9] = $laced[$at + 9] -bor 0x40

function Emit([string]$name, [byte[]]$g) {
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append("static const unsigned char GIF_$name[] = {")
    for ($i = 0; $i -lt $g.Length; $i++) {
        if ($i % 16 -eq 0) { [void]$sb.Append("`n    ") }
        [void]$sb.Append(("0x{0:X2}," -f $g[$i]))
    }
    [void]$sb.Append("`n};`n")
    return $sb.ToString()
}

$out = "/* Generated by tools/gengif.ps1 with Windows' GDI+ encoder: not by hand,`n" +
       "   and not by anything in this project. The palette is entry i =`n" +
       "   ((i*37)%256, (i*91)%256, (i*53+17)%256); see that script for each`n" +
       "   picture's indices. */`n"
$out += Emit "SMALL" $small
$out += Emit "NOISY" $noisy
$out += Emit "HOLES" $holes
$out += Emit "LACED" $laced
[System.IO.File]::WriteAllText((Join-Path $root "userland\gifdata.h"), $out, (New-Object System.Text.UTF8Encoding $false))
"wrote userland/gifdata.h: small $($small.Length), noisy $($noisy.Length), holes $($holes.Length), laced $($laced.Length) bytes"
