"""Builds the photographs userland/jpegtest.c decodes, as a C header.

JPEG is lossy, so this cannot check pixel for pixel the way the PNG test
does. What it checks instead is that the picture that comes back is the
picture that went in, to within what the format throws away: a red square is
red, an edge is where the edge was, and the colours are not swapped round —
which is the mistake a decoder actually makes, because brightness and the
two colour differences are easy to put back together in the wrong order.

The files are encoded by the host, through the drawing library Windows
already has. Nothing inside zelr uses it: userland/jpeg.h is the decoder,
and the point of this file is to have something it did not produce.

  python tools/genjpeg.py
"""
import base64
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "userland", "jpegdata.h")

# Each is a name, a size, and a function from (x, y) to a colour. They are
# chosen for what they catch:
#
#   flat      a solid colour, which must come back as that colour: the
#             simplest thing there is and the one that fails when the colour
#             conversion is wrong
#   quarters  four blocks of primary colours, which catches the two colour
#             channels being swapped — the picture still looks like a
#             picture, just wrong, so a person glancing at it would pass it
#   gradient  a smooth ramp, which is what the cosine transform is for and
#             what shows when the inverse is wrong
#   tall      a size that is not a multiple of eight, so the last blocks run
#             off the edge and have to be decoded and then thrown away
IMAGES = [
    ("flat", 32, 32, "if (true) { 200; 30; 40 }"),
    ("quarters", 64, 64, "quarters"),
    ("gradient", 48, 24, "gradient"),
    ("tall", 21, 37, "quarters"),
]

PS = r'''
Add-Type -AssemblyName System.Drawing
$b = New-Object System.Drawing.Bitmap %(w)d, %(h)d
for ($y = 0; $y -lt %(h)d; $y++) {
  for ($x = 0; $x -lt %(w)d; $x++) {
    %(body)s
    $b.SetPixel($x, $y, [System.Drawing.Color]::FromArgb($r, $g, $bl))
  }
}
$ms = New-Object System.IO.MemoryStream
$b.Save($ms, [System.Drawing.Imaging.ImageFormat]::Jpeg)
[Convert]::ToBase64String($ms.ToArray())
'''

BODIES = {
    "flat": "$r = 200; $g = 30; $bl = 40",
    "quarters": ("if ($x -lt %(hw)d) { if ($y -lt %(hh)d) "
                 "{ $r = 255; $g = 0; $bl = 0 } else { $r = 0; $g = 0; $bl = 255 } } "
                 "else { if ($y -lt %(hh)d) { $r = 0; $g = 255; $bl = 0 } "
                 "else { $r = 255; $g = 255; $bl = 255 } }"),
    "gradient": "$r = [int]($x * 255 / %(w)d); $g = $r; $bl = $r",
}


def encode(name, w, h):
    body = BODIES[name if name in BODIES else "quarters"]
    body = body % {"w": w, "h": h, "hw": w // 2, "hh": h // 2}
    script = PS % {"w": w, "h": h, "body": body}

    r = subprocess.run(["powershell", "-NoProfile", "-Command", script],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stderr[:400], file=sys.stderr)
        raise SystemExit("powershell could not encode %s" % name)
    return base64.b64decode(r.stdout.strip())


def carray(name, data):
    out = "static const u8 %s[%d] = {\n" % (name, len(data))
    for i in range(0, len(data), 16):
        out += "    " + ", ".join(str(b) for b in data[i:i + 16]) + ",\n"
    return out + "};\n\n"


def main():
    text = ['/* Generated by tools/genjpeg.py. Do not edit by hand.\n'
            '\n'
            '   Photographs for userland/jpegtest.c to decode, encoded by\n'
            '   something that is not the decoder. See that file for what\n'
            '   each one is for. */\n'
            '#pragma once\n'
            '#include "zelr.h"\n\n']

    for name, w, h, _ in IMAGES:
        data = encode(name, w, h)
        text.append("/* %d by %d */\n" % (w, h))
        text.append("#define JPG_%s_W %d\n" % (name.upper(), w))
        text.append("#define JPG_%s_H %d\n" % (name.upper(), h))
        text.append(carray("JPG_" + name.upper(), data))
        print("  %-9s %d by %d, %d bytes" % (name, w, h, len(data)))

    f = open(OUT, "w", newline="\n")
    f.write("".join(text))
    f.close()
    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
