#!/usr/bin/env python3
# The constant tables userland/aac.h decodes AAC with. Writes userland/aactab.h.
#
#   python tools/mkaac.py                 # fetches 3GPP TS 26.410 from 3gpp.org
#   python tools/mkaac.py 26410-j00.zip
#
# AAC's own specification (ISO/IEC 14496-3) is not free to read. The 3GPP
# edition of the codec, TS 26.410, is, and it prints the standard's tables
# inside its reference source rather than in its text. So the numbers -- and
# only the numbers -- are taken from that package's aac_rom.c: the twelve
# Huffman codebooks, the scale factor bands for each sampling rate, and the
# number of bands temporal noise shaping may reach. Nothing of the
# reference decoder is used; userland/aac.h is written from the standard's
# description of the stream.
#
# The codebooks there are stored as a search tree read two bits at a time,
# which is that decoder's own arrangement. Each is walked here and written
# out as plain codewords -- the bits, how many, and the values they stand
# for -- and checked: every book has the number of entries the standard
# gives it, no codeword is a prefix of another, and together they fill the
# code space exactly (the lengths' 2^-len sum to one). A book that fails any
# of these stops the script instead of reaching the header.
import hashlib
import io
import os
import re
import sys
import urllib.request
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
URL = "https://www.3gpp.org/ftp/Specs/archive/26_series/26.410/26410-j00.zip"
OUT = os.path.join(ROOT, "userland", "aactab.h")

# Entries, how many values a codeword stands for, and the offset that makes
# a stored value signed (the standard's "unsigned" books have none).
BOOKS = {
    1: (81, 4, 1), 2: (81, 4, 1), 3: (81, 4, 0), 4: (81, 4, 0),
    5: (81, 2, 4), 6: (81, 2, 4), 7: (64, 2, 0), 8: (64, 2, 0),
    9: (169, 2, 0), 10: (169, 2, 0), 11: (289, 2, 0),
}
FIELD_BITS = {4: 2, 2: 4}          # bits a value takes in the stored word
RATES = [48000, 44100, 32000, 24000, 22050, 16000, 12000, 11025, 8000]


def fetch(path):
    if path:
        raw = open(path, "rb").read()
    else:
        req = urllib.request.Request(URL, headers={"User-Agent": "Mozilla/5.0"})
        raw = urllib.request.urlopen(req, timeout=120).read()
    return raw, hashlib.sha256(raw).hexdigest()


def rom_source(raw):
    """aac_rom.c, out of the zip inside the zip."""
    outer = zipfile.ZipFile(io.BytesIO(raw))
    for name in outer.namelist():
        if name.endswith(".zip"):
            inner = zipfile.ZipFile(io.BytesIO(outer.read(name)))
            for n in inner.namelist():
                if n.endswith("FloatFR_aacdec/src/aac_rom.c"):
                    return inner.read(n).decode("latin-1"), name
    sys.exit("aac_rom.c is not in the package")


def table(src, name):
    """The numbers of one declared array, in order."""
    m = re.search(r"\b%s\b[^=]*=\s*\{" % re.escape(name), src)
    if not m:
        sys.exit("no table named " + name)
    i, depth = m.end(), 1
    j = i
    while depth:
        if src[j] == "{": depth += 1
        elif src[j] == "}": depth -= 1
        j += 1
    body = re.sub(r"/\*.*?\*/", "", src[i:j - 1], flags=re.S)
    return [int(x, 0) for x in re.findall(r"0x[0-9a-fA-F]+|-?\d+", body)]


def walk(nodes, value_bits):
    """Every codeword of a two-bits-a-step tree: (code, length, stored value)."""
    rows = [nodes[k:k + 4] for k in range(0, len(nodes), 4)]
    found = {}
    def step(row, code, length):
        for p in range(4):
            e = rows[row][p]
            c2, l2 = (code << 2) | p, length + 2
            if e & 1:
                if e & 2:                          # odd length: one bit was not its
                    c2, l2 = (code << 1) | (p >> 1), length + 1
                found[(c2, l2)] = (e >> 2) & ((1 << value_bits) - 1)
            else:
                step(e >> 2, c2, l2)
    step(0, 0, 0)
    return sorted(((c, l, v) for (c, l), v in found.items()), key=lambda t: (t[1], t[0]))


def check(name, codes, want):
    if len(codes) != want:
        sys.exit("%s has %d codewords, the standard gives %d" % (name, len(codes), want))
    kraft = sum(2.0 ** -l for _, l, _ in codes)
    if abs(kraft - 1.0) > 1e-12:
        sys.exit("%s does not fill its code space (%r)" % (name, kraft))
    for i, (c, l, _) in enumerate(codes):
        for c2, l2, _ in codes[i + 1:]:
            if l2 >= l and (c2 >> (l2 - l)) == c:
                sys.exit("%s: a codeword is the start of another" % name)


def main():
    raw, digest = fetch(sys.argv[1] if len(sys.argv) > 1 else None)
    src, inner = rom_source(raw)
    out = []
    out.append("/* Generated by tools/mkaac.py from 3GPP TS 26.410 (the numbers in its")
    out.append("   aac_rom.c only; see the script). Do not edit. Package sha256:")
    out.append("   %s (%s). */" % (digest, inner))
    out.append("#pragma once")
    out.append("")
    out.append("/* A codeword: its bits, how many, and the values it stands for (up to four,")
    out.append("   the first one first); the scale factor book's value is the difference. */")
    out.append("typedef struct { unsigned code; unsigned char len; signed char v[4]; } aac_hcode;")
    out.append("")
    for b, (want, dim, offset) in BOOKS.items():
        fbits = FIELD_BITS[dim] if b != 11 else 5
        codes = walk(table(src, "HuffmanCodeBook_%d" % b), fbits * dim)
        check("codebook %d" % b, codes, want)
        out.append("static const aac_hcode AAC_HCB%d[%d] = {" % (b, want))
        for c, l, v in codes:
            vals = [((v >> (fbits * k)) & ((1 << fbits) - 1)) - offset for k in range(dim)] + [0] * (4 - dim)
            out.append("    { 0x%x, %d, { %d, %d, %d, %d } }," % (c, l, *vals))
        out.append("};")
    scl = walk(table(src, "HuffmanCodeBook_SCL"), 8)
    check("the scale factor codebook", scl, 121)
    out.append("static const aac_hcode AAC_HCB_SF[121] = {")
    for c, l, v in scl:
        out.append("    { 0x%x, %d, { %d, 0, 0, 0 } }," % (c, l, v - 60))
    out.append("};")
    out.append("")

    # The bands, by the table that says which rate uses which.
    info = re.search(r"SamplingRateInfoTable\[9\]\s*=\s*\{(.*?)\};", src, re.S).group(1)
    rows = re.findall(r"\{\s*(\d+),\s*(\d+),\s*(\w+),\s*(\d+),\s*(\w+)\s*\}", info)
    if [int(r[0]) for r in rows] != RATES:
        sys.exit("the sampling rate table is not the nine rates expected")
    named = {}
    for r in rows:
        for nm, count in ((r[2], int(r[1])), (r[4], int(r[3]))):
            t = table(src, nm)
            if len(t) != count + 1 or t[0] != 0 or t[-1] not in (1024, 128) or t != sorted(t):
                sys.exit("band table %s is not %d bands from 0 to the end" % (nm, count))
            named[nm] = t
    for nm, t in named.items():
        out.append("static const short AAC_%s[%d] = { %s };" % (nm.upper(), len(t), ", ".join(map(str, t))))
    out.append("")
    out.append("/* For each rate this decoder takes: how many bands a long and a short window")
    out.append("   have and where they start, and how far temporal noise shaping may reach. */")
    out.append("typedef struct { int rate, nlong; const short *lng; int nshort; const short *shrt; int tns_long, tns_short; } aac_rate;")
    tns = table(src, "tns_max_bands_tbl")
    if len(tns) != 18:
        sys.exit("the noise shaping table is not nine pairs")
    out.append("static const aac_rate AAC_RATES[9] = {")
    for k, r in enumerate(rows):
        out.append("    { %s, %s, AAC_%s, %s, AAC_%s, %d, %d }," % (r[0], r[1], r[2].upper(), r[3], r[4].upper(), tns[2 * k], tns[2 * k + 1]))
    out.append("};")
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", OUT, "from", inner)


if __name__ == "__main__":
    main()
