/* An H.264 (AVC) decoder, written from ITU-T H.264.
 *
 * What a live stream sends: Baseline, Main and High profile, progressive
 * frames in 4:2:0 at 8 bits, CAVLC or CABAC, I, P and B slices with any
 * number of slices a picture, weighted prediction (explicit and implicit),
 * spatial and temporal direct, the 8x8 transform and scaling matrices,
 * long-term references and memory management, and output in display order.
 * Refused by name rather than decoded wrongly: fields (PAFF and MBAFF),
 * other chroma formats and bit depths, slice groups, data partitioning,
 * and SP and SI slices.
 *
 * Feed it access units (h264_decode_au, a transport stream's PES packets)
 * or NAL units (h264_nal, h264_next_nal splitting an Annex B buffer), and
 * take frames from it (h264_frame) as they become due, before decoding
 * more once h264_room says there is no frame free; h264_flush makes the
 * rest due at the end. A picture is the planes of the frame it decoded
 * into, valid until the next call to h264_frame.
 *
 * The numbers (CABAC contexts, variable-length codes, scans, filter
 * thresholds) are in h264tab.h, generated by tools/mkh264.py from ITU-T's
 * reference decoder. The parts are h264mb.h (entropy decoding of a
 * macroblock) and h264rec.h (prediction, the transforms and the deblocking
 * filter); this file is the stream around them.
 */
#pragma once
#ifndef H264_NO_ZELR
#include "zelr.h"
#include "alloc.h"
#define h264_alloc(n) calloc(n)
#define h264_free(p) free(p)
#endif
#include "h264tab.h"

#define H264_MAX_SPS 32
#define H264_MAX_PPS 256
#define H264_MAX_LIST 32
#define H264_DPB 18                    /* sixteen references, the current one and one waiting */

typedef struct {
    int present;
    int profile_idc, level_idc, chroma_format_idc;
    int bit_depth_luma, bit_depth_chroma, bypass;
    int log2_max_frame_num, poc_type, log2_max_poc_lsb;
    int delta_pic_order_always_zero, offset_for_non_ref_pic, offset_for_top_to_bottom_field;
    int poc_cycle, offset_for_ref_frame[256];
    int max_num_ref_frames, gaps_allowed;
    int mb_w, mb_h, frame_mbs_only, mbaff, direct_8x8_inference;
    int crop_l, crop_r, crop_t, crop_b;        /* in luma samples */
    int scaling_present;
    u8 sl4[6][16], sl8[2][64];                 /* raster order */
    int num_reorder, max_dec_buffering;        /* -1 when the stream does not say */
    int full_range, matrix;
} h264_sps;

typedef struct {
    int present, sps_id, cabac, bottom_field_poc, slice_groups;
    int num_ref_idx_default[2], weighted_pred, weighted_bipred;
    int init_qp, init_qs, chroma_qp_offset[2], deblock_control, constrained_intra, redundant_pic_cnt;
    int transform_8x8, scaling_present;
    u8 sl4[6][16], sl8[2][64];                 /* raster order, after the fall-back rules */
} h264_pps;

typedef struct h264_pic {
    u8 *y, *cb, *cr;
    short (*mv)[2][16][2];                     /* each macroblock's 4x4 blocks, raster order */
    signed char (*ri)[2][4];                   /* each 8x8's reference index, -1 none */
    int (*refid)[2][4];                        /* and the picture it is, by id */
    u8 *intra;
    int poc, frame_num, frame_num_wrap, lt_idx;
    int ref;                                   /* 0 none, 1 short-term, 2 long-term */
    int wait_output, id, nonexisting, in_use;
    int idr_like;                              /* an IDR or after memory management 5 */
    int epoch;                                 /* which run of picture order it belongs to */
    long long pts;                             /* the time its access unit carried */
} h264_pic;

enum { H264_P = 0, H264_B = 1, H264_I = 2, H264_SP = 3, H264_SI = 4 };

typedef struct {
    int first_mb, type, pps_id, frame_num, idr, idr_pic_id, nal_ref_idc, nal_type;
    int poc_lsb, delta_poc_bottom, delta_poc[2], redundant_pic_cnt;
    int direct_spatial, num_ref[2], cabac_init_idc, qp, deblock_idc, alpha_off, beta_off;
    int long_term_ref, no_output_prior, adaptive_marking, n_mmco, mmco[72][3];
    int mod[2][33][2], n_mod[2];
    int luma_denom, chroma_denom;
    short lw[2][H264_MAX_LIST], lo[2][H264_MAX_LIST], cw[2][H264_MAX_LIST][2], co[2][H264_MAX_LIST][2];
    u8 lwflag[2][H264_MAX_LIST], cwflag[2][H264_MAX_LIST];
    h264_pic *list[2][H264_MAX_LIST + 1];       /* one longer: a change inserts before it removes */
    short implicit[H264_MAX_LIST][H264_MAX_LIST]; /* w1 of implicit weights; w0 = 64 - w1 */
    int number;                                /* this slice's number in its picture */
} h264_slice;

/* What a decoded frame is, for whoever shows it. */
typedef struct {
    const u8 *y, *cb, *cr;
    int stride_y, stride_c;                    /* in bytes */
    int width, height;                         /* after cropping */
    int poc, full_range, matrix;
    long long pts;                             /* as given to h264_decode_au with its access unit */
} h264_picture;

typedef struct h264_bits { const u8 *p; int n, pos; } h264_bits;

typedef struct h264_dec h264_dec;

/* The macroblock being decoded: what its syntax said, before it is
   predicted and its residual added. Coefficients are kept in raster order
   within their block, already dequantised. */
typedef struct {
    int addr, x, y;                            /* address, and column and row in macroblocks */
    int kind;                                  /* H264_K_* */
    int i16mode, cbp, t8, qp, cpred;
    int parts;                                 /* 1 (16x16), 2 (16x8), 3 (8x16) or 4 (8x8) */
    int pred[4];                               /* each partition: bit 0 list 0, bit 1 list 1 */
    int sub[4];                                /* each 8x8: sub-partitions, 1, 2 (8x4), 3 (4x8) or 4 */
    int subpred[4];
    int ref[2][4];                             /* each 8x8's reference index, as sent */
    int no_small;                              /* no partition smaller than 8x8 (the 8x8 transform's condition) */
    short mvd[2][16][2];                       /* each 4x4 block's (raster) mvd */
    signed char ipm[16];                       /* each 4x4 block's intra mode (raster) */
    int coded;                                 /* luma 4x4 blocks with coefficients, by raster bit */
    int dc_coded, cdc_coded, cac_coded;        /* luma DC; chroma DC by component; chroma AC by bit */
    short coef[16][16];
    short coef8[4][64];
    short dc[16];
    short cdc[2][4];
    short cac[2][4][16];
    u8 pcm[384];
    u16 done;                                  /* 4x4 blocks whose motion is known, by raster bit */
} h264_mbctx;

/* What a stream has used, for a check to say what it covered. */
enum {
    H264_SEEN_CAVLC = 1, H264_SEEN_CABAC = 2, H264_SEEN_B = 4, H264_SEEN_T8 = 8, H264_SEEN_INTRA8 = 16,
    H264_SEEN_SPATIAL = 32, H264_SEEN_TEMPORAL = 64, H264_SEEN_EXPLICIT = 128, H264_SEEN_IMPLICIT = 256,
    H264_SEEN_MULTIREF = 512, H264_SEEN_LONGTERM = 1024, H264_SEEN_MMCO = 2048, H264_SEEN_PCM = 4096,
    H264_SEEN_SCALING = 8192, H264_SEEN_SLICES = 16384, H264_SEEN_INTRA_IN_P = 32768,
};
static const char *const H264_SEEN_NAMES[16] = {
    "cavlc", "cabac", "b pictures", "8x8 transform", "intra 8x8", "spatial direct", "temporal direct",
    "explicit weights", "implicit weights", "several references", "long-term references",
    "memory management", "pcm", "scaling matrices", "several slices", "intra in predicted pictures",
};

enum {
    H264_K_INTRA = 1, H264_K_INXN = 2, H264_K_I16 = 4, H264_K_PCM = 8,
    H264_K_SKIP = 16, H264_K_DIRECT = 32, H264_K_B8X8 = 64,
};

struct h264_dec {
    h264_sps sps[H264_MAX_SPS];
    h264_pps pps[H264_MAX_PPS];
    const h264_sps *sp;
    const h264_pps *pp;
    int mb_w, mb_h, mbs;                       /* the size the buffers below were made for */
    int npics;                                 /* frames made, of H264_DPB */
    long long next_pts;                        /* given to the next picture begun (h264_decode_au) */
    h264_pic dpb[H264_DPB];
    int dpb_size;                              /* frames the stream may keep (references and waiting) */
    h264_pic *cur;
    h264_slice sl;
    int slices;                                /* slices begun in this picture */
    int first_slice_qp_seen;

    /* Each macroblock of the picture being decoded. */
    short *mb_slice;                           /* slice number, -1 not decoded yet */
    u8 *mb_kind, *mb_cbp, *mb_t8, *mb_cpred;
    signed char *mb_qp, *mb_qpc[2];
    u32 *mb_cbf;
    u8 (*nzc)[24];
    signed char (*ipm)[16];
    u8 (*mvd)[2][16][2];
    u8 *mb_direct8;                            /* which 8x8s were predicted by direct */
    u16 *mb_nz;                                /* luma 4x4s inside a transform block with coefficients */
    u8 *mb_dbidc;                              /* each macroblock's slice's filter settings */
    signed char *mb_alpha, *mb_beta;
    h264_mbctx m;                              /* the macroblock being decoded */
    int ls4[6][6][16], ls8[2][6][64];          /* LevelScale for each list and qP % 6 */
    int epoch;

    /* Entropy decoding of the slice being read. */
    const u8 *data;
    int data_n, pos;                           /* bit position, for CAVLC and the CABAC engine alike */
    u32 range, offset;
    u8 ctx[1024];
    int qp_prev, last_dqp;

    /* Picture order and reference state. */
    int prev_poc_msb, prev_poc_lsb, prev_frame_num_offset, prev_frame_num, prev_ref_frame_num;
    int prev_mmco5, prev_ref_poc_after_mmco5;
    int max_lt_idx;                            /* -1 none */
    int next_id;
    int max_frame_num;

    u8 *rbsp;
    int rbsp_cap;

    /* Output, in display order. */
    h264_pic *shown;                           /* handed out last; reusable when the next is asked for */
    int flushing;

    /* Counts, for tests and for saying what went wrong. */
    int frames_decoded, frames_out, mbs_decoded, errors;
    u32 seen;                                  /* H264_SEEN_*: what the stream has used */
    char why[96];
};

static void h264_say(h264_dec *d, const char *s) {
    int i = 0;
    for (; s[i] && i < (int)sizeof(d->why) - 1; i++) d->why[i] = s[i];
    d->why[i] = 0;
    d->errors++;
}

static inline int h264_clip3(int lo, int hi, int v) { return v < lo ? lo : v > hi ? hi : v; }
static inline int h264_min(int a, int b) { return a < b ? a : b; }
static inline int h264_max(int a, int b) { return a > b ? a : b; }
static inline int h264_abs(int a) { return a < 0 ? -a : a; }

/* --- reading bits -------------------------------------------------------------------------- */

static inline u32 hb_peek(const h264_bits *b, int k) {   /* k <= 25 */
    int at = b->pos >> 3;
    u32 v = 0;
    for (int i = 0; i < 4; i++) v = (v << 8) | (u32)(at + i < b->n ? b->p[at + i] : 0);
    return (v << (b->pos & 7)) >> (32 - k);
}
static inline u32 hb_u(h264_bits *b, int k) {
    if (!k) return 0;
    if (k > 24) { u32 hi = hb_u(b, k - 16); return (hi << 16) | hb_u(b, 16); }
    u32 v = hb_peek(b, k);
    b->pos += k;
    return v;
}
static inline int hb_bit(h264_bits *b) {
    int at = b->pos >> 3;
    int v = at < b->n ? (b->p[at] >> (7 - (b->pos & 7))) & 1 : 0;
    b->pos++;
    return v;
}
/* An Exp-Golomb number. A damaged one can say anything up to 2^32 - 2;
   it is held to H264_UE_MAX, so that as an int it is never negative and
   every range check after it refuses it. */
#define H264_UE_MAX 0x7FFFFFFu
static inline u32 hb_ue(h264_bits *b) {
    int z = 0;
    while (z < 32 && !hb_bit(b)) z++;
    if (z >= 27) { if (z < 32) hb_u(b, z); return H264_UE_MAX; }
    u32 v = ((1u << z) - 1) + hb_u(b, z);
    return v > H264_UE_MAX ? H264_UE_MAX : v;
}
static inline int hb_se(h264_bits *b) {
    u32 k = hb_ue(b);
    return (k & 1) ? (int)((k + 1) >> 1) : -(int)(k >> 1);
}
static inline int hb_over(const h264_bits *b) { return b->pos > b->n * 8; }

/* Whether anything but the stop bit and its trailing zeros is left. */
static int hb_more(const h264_bits *b) {
    int last = b->n - 1;
    while (last >= 0 && !b->p[last]) last--;
    if (last < 0) return 0;
    int bit = 0;
    while (!((b->p[last] >> bit) & 1)) bit++;
    return b->pos < last * 8 + (7 - bit);
}

/* --- parameter sets ------------------------------------------------------------------------ */

/* 7.3.2.1.1.1: a scaling list in zig-zag order; returns 1 when it asks for
   the default. */
static int h264_scaling_list(h264_bits *b, u8 *out, int n) {
    int last = 8, next = 8;
    const u8 *zz = n == 16 ? H264_ZIGZAG4 : H264_ZIGZAG8;
    for (int j = 0; j < n; j++) {
        if (next) {
            int delta = hb_se(b);
            next = (last + delta + 256) % 256;
            if (j == 0 && next == 0) return 1;
        }
        int v = next ? next : last;
        out[zz[j]] = (u8)v;
        last = v;
    }
    return 0;
}

static void h264_copy(u8 *d, const u8 *s, int n) { for (int i = 0; i < n; i++) d[i] = s[i]; }

/* The lists of an SPS or PPS, with fall-back rule A (from the defaults) or
   B (from the sequence's lists). */
static void h264_scaling_lists(h264_bits *b, u8 sl4[6][16], u8 sl8[2][64], int n8,
                               const u8 fb4[6][16], const u8 fb8[2][64], int rule_a) {
    for (int i = 0; i < 6 + n8; i++) {
        int present = hb_bit(b);
        if (i < 6) {
            const u8 *def = i < 3 ? H264_DEFAULT4_INTRA : H264_DEFAULT4_INTER;
            if (present) {
                if (h264_scaling_list(b, sl4[i], 16)) h264_copy(sl4[i], def, 16);
            } else if (i == 0 || i == 3) {
                h264_copy(sl4[i], rule_a ? def : fb4[i], 16);
            } else {
                h264_copy(sl4[i], sl4[i - 1], 16);
            }
        } else {
            int k = i - 6;
            const u8 *def = k == 0 ? H264_DEFAULT8_INTRA : H264_DEFAULT8_INTER;
            if (present) {
                if (h264_scaling_list(b, sl8[k], 64)) h264_copy(sl8[k], def, 64);
            } else {
                h264_copy(sl8[k], rule_a ? def : fb8[k], 64);
            }
        }
    }
}

static void h264_flat(u8 sl4[6][16], u8 sl8[2][64]) {
    for (int i = 0; i < 6; i++) for (int j = 0; j < 16; j++) sl4[i][j] = 16;
    for (int i = 0; i < 2; i++) for (int j = 0; j < 64; j++) sl8[i][j] = 16;
}

static void h264_hrd(h264_bits *b) {
    int n = (int)hb_ue(b) + 1;
    hb_u(b, 8);
    for (int i = 0; i < n && i < 32; i++) { hb_ue(b); hb_ue(b); hb_bit(b); }
    hb_u(b, 20);
}

static int h264_parse_sps(h264_dec *d, h264_bits *b) {
    int profile = (int)hb_u(b, 8);
    hb_u(b, 8);                                /* constraint flags */
    int level = (int)hb_u(b, 8);
    u32 id = hb_ue(b);
    if (id >= H264_MAX_SPS) { h264_say(d, "a sequence parameter set with a bad number"); return -1; }
    static h264_sps s;                         /* the struct is too big to want on the stack twice */
    for (int i = 0; i < (int)sizeof(s); i++) ((volatile u8 *)&s)[i] = 0;
    s.profile_idc = profile;
    s.level_idc = level;
    s.chroma_format_idc = 1;
    s.bit_depth_luma = s.bit_depth_chroma = 8;
    h264_flat(s.sl4, s.sl8);
    if (profile == 100 || profile == 110 || profile == 122 || profile == 244 || profile == 44 ||
        profile == 83 || profile == 86 || profile == 118 || profile == 128 || profile == 138 ||
        profile == 139 || profile == 134 || profile == 135) {
        s.chroma_format_idc = (int)hb_ue(b);
        if (s.chroma_format_idc == 3) hb_bit(b);   /* separate_colour_plane_flag */
        s.bit_depth_luma = (int)hb_ue(b) + 8;
        s.bit_depth_chroma = (int)hb_ue(b) + 8;
        s.bypass = hb_bit(b);
        s.scaling_present = hb_bit(b);
        if (s.scaling_present)
            h264_scaling_lists(b, s.sl4, s.sl8, s.chroma_format_idc == 3 ? 6 : 2, s.sl4, s.sl8, 1);
    }
    s.log2_max_frame_num = (int)hb_ue(b) + 4;
    s.poc_type = (int)hb_ue(b);
    if (s.poc_type == 0) {
        s.log2_max_poc_lsb = (int)hb_ue(b) + 4;
    } else if (s.poc_type == 1) {
        s.delta_pic_order_always_zero = hb_bit(b);
        s.offset_for_non_ref_pic = hb_se(b);
        s.offset_for_top_to_bottom_field = hb_se(b);
        s.poc_cycle = (int)hb_ue(b);
        if (s.poc_cycle > 255) { h264_say(d, "a picture order cycle too long"); return -1; }
        for (int i = 0; i < s.poc_cycle; i++) s.offset_for_ref_frame[i] = hb_se(b);
    }
    s.max_num_ref_frames = (int)hb_ue(b);
    s.gaps_allowed = hb_bit(b);
    s.mb_w = (int)hb_ue(b) + 1;
    s.mb_h = (int)hb_ue(b) + 1;
    s.frame_mbs_only = hb_bit(b);
    if (!s.frame_mbs_only) { s.mbaff = hb_bit(b); s.mb_h *= 2; }
    s.direct_8x8_inference = hb_bit(b);
    if (hb_bit(b)) {
        int l = (int)hb_ue(b), r = (int)hb_ue(b), t = (int)hb_ue(b), bo = (int)hb_ue(b);
        int cx = s.chroma_format_idc ? 2 : 1, cy = (s.chroma_format_idc == 1 ? 2 : 1) * (2 - s.frame_mbs_only);
        s.crop_l = l * cx; s.crop_r = r * cx; s.crop_t = t * cy; s.crop_b = bo * cy;
    }
    s.num_reorder = s.max_dec_buffering = -1;
    s.matrix = 2;                              /* unspecified */
    if (hb_bit(b)) {                           /* VUI */
        if (hb_bit(b)) { if (hb_u(b, 8) == 255) hb_u(b, 32); }
        if (hb_bit(b)) hb_bit(b);
        if (hb_bit(b)) {
            hb_u(b, 3);
            s.full_range = hb_bit(b);
            if (hb_bit(b)) { hb_u(b, 8); hb_u(b, 8); s.matrix = (int)hb_u(b, 8); }
        }
        if (hb_bit(b)) { hb_ue(b); hb_ue(b); }
        if (hb_bit(b)) { hb_u(b, 32); hb_u(b, 32); hb_bit(b); }
        int nal = hb_bit(b);
        if (nal) h264_hrd(b);
        int vcl = hb_bit(b);
        if (vcl) h264_hrd(b);
        if (nal || vcl) hb_bit(b);
        hb_bit(b);                             /* pic_struct_present_flag */
        if (hb_bit(b)) {
            hb_bit(b); hb_ue(b); hb_ue(b); hb_ue(b); hb_ue(b);
            s.num_reorder = (int)hb_ue(b);
            s.max_dec_buffering = (int)hb_ue(b);
        }
    }
    if (hb_over(b)) { h264_say(d, "a sequence parameter set that stops short"); return -1; }
    /* What the standard allows and no further: these size shifts and
       buffers below. */
    if (s.log2_max_frame_num > 16 || s.log2_max_poc_lsb > 16 || s.poc_type > 2 || s.max_num_ref_frames > 16 ||
        s.mb_w > 256 || s.mb_h > 256 || s.crop_l + s.crop_r >= s.mb_w * 16 || s.crop_t + s.crop_b >= s.mb_h * 16) {
        h264_say(d, "a sequence parameter set out of range");
        return -1;
    }
    s.present = 1;
    h264_sps *to = &d->sps[id];
    for (int i = 0; i < (int)sizeof(s); i++) ((volatile u8 *)to)[i] = ((u8 *)&s)[i];
    return 0;
}

static int h264_parse_pps(h264_dec *d, h264_bits *b) {
    u32 id = hb_ue(b), sid = hb_ue(b);
    if (id >= H264_MAX_PPS || sid >= H264_MAX_SPS || !d->sps[sid].present) {
        h264_say(d, "a picture parameter set for no sequence");
        return -1;
    }
    const h264_sps *sp = &d->sps[sid];
    h264_pps *p = &d->pps[id];
    for (int i = 0; i < (int)sizeof(*p); i++) ((volatile u8 *)p)[i] = 0;
    p->sps_id = (int)sid;
    p->cabac = hb_bit(b);
    p->bottom_field_poc = hb_bit(b);
    p->slice_groups = (int)hb_ue(b) + 1;
    if (p->slice_groups > 1) { h264_say(d, "slice groups (FMO), which this does not decode"); return -1; }
    p->num_ref_idx_default[0] = (int)hb_ue(b) + 1;
    p->num_ref_idx_default[1] = (int)hb_ue(b) + 1;
    p->weighted_pred = hb_bit(b);
    p->weighted_bipred = (int)hb_u(b, 2);
    p->init_qp = 26 + hb_se(b);
    p->init_qs = 26 + hb_se(b);
    p->chroma_qp_offset[0] = hb_se(b);
    p->deblock_control = hb_bit(b);
    p->constrained_intra = hb_bit(b);
    p->redundant_pic_cnt = hb_bit(b);
    p->chroma_qp_offset[1] = p->chroma_qp_offset[0];
    for (int i = 0; i < 6; i++) h264_copy(p->sl4[i], sp->sl4[i], 16);
    for (int i = 0; i < 2; i++) h264_copy(p->sl8[i], sp->sl8[i], 64);
    if (hb_more(b)) {
        p->transform_8x8 = hb_bit(b);
        p->scaling_present = hb_bit(b);
        if (p->scaling_present)
            h264_scaling_lists(b, p->sl4, p->sl8, p->transform_8x8 ? (sp->chroma_format_idc == 3 ? 6 : 2) : 0,
                               sp->sl4, sp->sl8, !sp->scaling_present);
        p->chroma_qp_offset[1] = hb_se(b);
    }
    if (hb_over(b)) { h264_say(d, "a picture parameter set that stops short"); return -1; }
    p->present = 1;
    return 0;
}

/* --- pictures ------------------------------------------------------------------------------ */

static void h264_free_pics(h264_dec *d) {
    for (int i = 0; i < H264_DPB; i++) {
        h264_pic *p = &d->dpb[i];
        if (p->y) h264_free(p->y);
        if (p->mv) h264_free(p->mv);
        if (p->ri) h264_free(p->ri);
        if (p->refid) h264_free(p->refid);
        if (p->intra) h264_free(p->intra);
        for (int j = 0; j < (int)sizeof(*p); j++) ((volatile u8 *)p)[j] = 0;
    }
    void **arrays[] = { (void **)&d->mb_slice, (void **)&d->mb_kind, (void **)&d->mb_cbp, (void **)&d->mb_t8,
                        (void **)&d->mb_cpred, (void **)&d->mb_qp, (void **)&d->mb_qpc[0], (void **)&d->mb_qpc[1],
                        (void **)&d->mb_cbf, (void **)&d->nzc, (void **)&d->ipm, (void **)&d->mvd,
                        (void **)&d->mb_direct8, (void **)&d->mb_dbidc, (void **)&d->mb_alpha,
                        (void **)&d->mb_beta, (void **)&d->mb_nz };
    for (int i = 0; i < (int)(sizeof(arrays) / sizeof(arrays[0])); i++) {
        if (*arrays[i]) h264_free(*arrays[i]);
        *arrays[i] = 0;
    }
    d->mbs = d->mb_w = d->mb_h = d->npics = 0;
}

/* Buffers for a new picture size; 0 when there is not the memory. */
static int h264_make_pics(h264_dec *d, int mb_w, int mb_h, int n) {
    h264_free_pics(d);
    int mbs = mb_w * mb_h;
    u64 luma = (u64)mbs * 256, chroma = (u64)mbs * 64;
    for (int i = 0; i < n; i++) {
        h264_pic *p = &d->dpb[i];
        p->y = (u8 *)h264_alloc(luma + 2 * chroma);
        p->mv = (short (*)[2][16][2])h264_alloc((u64)mbs * sizeof(*p->mv));
        p->ri = (signed char (*)[2][4])h264_alloc((u64)mbs * sizeof(*p->ri));
        p->refid = (int (*)[2][4])h264_alloc((u64)mbs * sizeof(*p->refid));
        p->intra = (u8 *)h264_alloc((u64)mbs);
        if (!p->y || !p->mv || !p->ri || !p->refid || !p->intra) { h264_free_pics(d); return 0; }
        p->cb = p->y + luma;
        p->cr = p->cb + chroma;
    }
    d->mb_slice = (short *)h264_alloc((u64)mbs * 2);
    d->mb_kind = (u8 *)h264_alloc((u64)mbs);
    d->mb_cbp = (u8 *)h264_alloc((u64)mbs);
    d->mb_t8 = (u8 *)h264_alloc((u64)mbs);
    d->mb_cpred = (u8 *)h264_alloc((u64)mbs);
    d->mb_qp = (signed char *)h264_alloc((u64)mbs);
    d->mb_qpc[0] = (signed char *)h264_alloc((u64)mbs);
    d->mb_qpc[1] = (signed char *)h264_alloc((u64)mbs);
    d->mb_cbf = (u32 *)h264_alloc((u64)mbs * 4);
    d->nzc = (u8 (*)[24])h264_alloc((u64)mbs * 24);
    d->ipm = (signed char (*)[16])h264_alloc((u64)mbs * 16);
    d->mvd = (u8 (*)[2][16][2])h264_alloc((u64)mbs * 64);
    d->mb_direct8 = (u8 *)h264_alloc((u64)mbs);
    d->mb_dbidc = (u8 *)h264_alloc((u64)mbs);
    d->mb_alpha = (signed char *)h264_alloc((u64)mbs);
    d->mb_beta = (signed char *)h264_alloc((u64)mbs);
    d->mb_nz = (u16 *)h264_alloc((u64)mbs * 2);
    if (!d->mb_nz ||
        !d->mb_slice || !d->mb_kind || !d->mb_cbp || !d->mb_t8 || !d->mb_cpred || !d->mb_qp ||
        !d->mb_qpc[0] || !d->mb_qpc[1] || !d->mb_cbf || !d->nzc || !d->ipm || !d->mvd || !d->mb_direct8 ||
        !d->mb_dbidc || !d->mb_alpha || !d->mb_beta) {
        h264_free_pics(d);
        return 0;
    }
    d->mb_w = mb_w;
    d->mb_h = mb_h;
    d->mbs = mbs;
    d->npics = n;
    return 1;
}

/* How many frames this stream's decoder must be able to hold (A.3.1). */
static int h264_dpb_frames(const h264_sps *s) {
    static const struct { int level, mbs; } MAX_DPB_MBS[] = {
        { 9, 396 }, { 10, 396 }, { 11, 900 }, { 12, 2376 }, { 13, 2376 }, { 20, 2376 }, { 21, 4752 },
        { 22, 8100 }, { 30, 8100 }, { 31, 18000 }, { 32, 20480 }, { 40, 32768 }, { 41, 32768 },
        { 42, 34816 }, { 50, 110400 }, { 51, 184320 }, { 52, 184320 }, { 60, 696320 }, { 61, 696320 }, { 62, 696320 },
    };
    int mbs = 0;
    for (int i = 0; i < (int)(sizeof(MAX_DPB_MBS) / sizeof(MAX_DPB_MBS[0])); i++)
        if (MAX_DPB_MBS[i].level == s->level_idc) mbs = MAX_DPB_MBS[i].mbs;
    int n = mbs ? mbs / (s->mb_w * s->mb_h) : 16;
    if (s->max_dec_buffering >= 0) n = s->max_dec_buffering;
    if (n < s->max_num_ref_frames) n = s->max_num_ref_frames;
    if (n < 1) n = 1;
    if (n > 16) n = 16;
    return n;
}

static void h264_scales(h264_dec *d);

static int h264_activate(h264_dec *d, const h264_pps *pp) {
    const h264_sps *sp = &d->sps[pp->sps_id];
    if (!sp->frame_mbs_only) { h264_say(d, "interlaced (field) coding, which this does not decode"); return -1; }
    if (sp->chroma_format_idc != 1) { h264_say(d, "a chroma format other than 4:2:0"); return -1; }
    if (sp->bit_depth_luma != 8 || sp->bit_depth_chroma != 8) { h264_say(d, "samples of more than 8 bits"); return -1; }
    if (sp->bypass) { h264_say(d, "lossless coding, which this does not decode"); return -1; }
    if (sp->mb_w * sp->mb_h > 8704) { h264_say(d, "a picture larger than 2048x1088"); return -1; }
    /* As many frames as the stream may keep, the one being decoded, the one
       handed out and one to spare: a 1080p stream at level 4.2 keeps four,
       so it needs seven, where a buffer of the most there could be would
       be eighteen at 4.5 MB each. */
    int dpb = h264_dpb_frames(sp);
    int want = h264_min(H264_DPB, dpb + 3);
    if (sp->mb_w != d->mb_w || sp->mb_h != d->mb_h || !d->mbs || d->npics < want) {
        if (d->cur) { h264_say(d, "the picture size changed inside a picture"); return -1; }
        if (!h264_make_pics(d, sp->mb_w, sp->mb_h, want)) { h264_say(d, "not enough memory for the pictures"); return -1; }
    }
    d->sp = sp;
    d->pp = pp;
    d->dpb_size = dpb;
    d->max_frame_num = 1 << sp->log2_max_frame_num;
    h264_scales(d);
    return 0;
}

/* --- the slice header ---------------------------------------------------------------------- */

static void h264_weights(h264_dec *d, h264_bits *b) {
    h264_slice *s = &d->sl;
    s->luma_denom = (int)hb_ue(b);
    s->chroma_denom = (int)hb_ue(b);
    if (s->luma_denom > 7 || s->chroma_denom > 7) { s->luma_denom = s->chroma_denom = 0; return; }
    for (int l = 0; l < (s->type == H264_B ? 2 : 1); l++) {
        for (int i = 0; i < s->num_ref[l]; i++) {
            s->lw[l][i] = (short)(1 << s->luma_denom);
            s->lo[l][i] = 0;
            s->lwflag[l][i] = (u8)hb_bit(b);
            if (s->lwflag[l][i]) { s->lw[l][i] = (short)hb_se(b); s->lo[l][i] = (short)hb_se(b); }
            s->cwflag[l][i] = (u8)hb_bit(b);
            for (int c = 0; c < 2; c++) { s->cw[l][i][c] = (short)(1 << s->chroma_denom); s->co[l][i][c] = 0; }
            if (s->cwflag[l][i])
                for (int c = 0; c < 2; c++) { s->cw[l][i][c] = (short)hb_se(b); s->co[l][i][c] = (short)hb_se(b); }
        }
    }
}

static int h264_slice_header(h264_dec *d, h264_bits *b, int nal_type, int nal_ref_idc) {
    h264_slice *s = &d->sl;
    s->nal_type = nal_type;
    s->nal_ref_idc = nal_ref_idc;
    s->idr = nal_type == 5;
    s->first_mb = (int)hb_ue(b);
    int t = (int)hb_ue(b);
    s->type = t % 5;
    s->pps_id = (int)hb_ue(b);
    if (s->pps_id >= H264_MAX_PPS || !d->pps[s->pps_id].present) { h264_say(d, "a slice for no picture parameter set"); return -1; }
    if (s->type == H264_SP || s->type == H264_SI) { h264_say(d, "SP and SI slices, which this does not decode"); return -1; }
    const h264_pps *pp = &d->pps[s->pps_id];
    const h264_sps *sp = &d->sps[pp->sps_id];
    if (!sp->present) { h264_say(d, "a slice for no sequence parameter set"); return -1; }
    s->frame_num = (int)hb_u(b, sp->log2_max_frame_num);
    if (!sp->frame_mbs_only) { h264_say(d, "interlaced (field) coding, which this does not decode"); return -1; }
    if (s->idr) s->idr_pic_id = (int)hb_ue(b);
    s->poc_lsb = s->delta_poc_bottom = s->delta_poc[0] = s->delta_poc[1] = 0;
    if (sp->poc_type == 0) {
        s->poc_lsb = (int)hb_u(b, sp->log2_max_poc_lsb);
        if (pp->bottom_field_poc) s->delta_poc_bottom = hb_se(b);
    }
    if (sp->poc_type == 1 && !sp->delta_pic_order_always_zero) {
        s->delta_poc[0] = hb_se(b);
        if (pp->bottom_field_poc) s->delta_poc[1] = hb_se(b);
    }
    s->redundant_pic_cnt = pp->redundant_pic_cnt ? (int)hb_ue(b) : 0;
    s->direct_spatial = s->type == H264_B ? hb_bit(b) : 0;
    s->num_ref[0] = pp->num_ref_idx_default[0];
    s->num_ref[1] = pp->num_ref_idx_default[1];
    if (s->type == H264_P || s->type == H264_B) {
        if (hb_bit(b)) {
            s->num_ref[0] = (int)hb_ue(b) + 1;
            if (s->type == H264_B) s->num_ref[1] = (int)hb_ue(b) + 1;
        }
    }
    if (s->type != H264_B) s->num_ref[1] = 0;
    if (s->type == H264_I) s->num_ref[0] = 0;
    if (s->num_ref[0] > H264_MAX_LIST || s->num_ref[1] > H264_MAX_LIST) { h264_say(d, "too many references in a slice"); return -1; }
    s->n_mod[0] = s->n_mod[1] = 0;
    for (int l = 0; l < 2; l++) {
        if ((l == 0 && s->type != H264_I) || (l == 1 && s->type == H264_B)) {
            if (hb_bit(b)) {
                for (;;) {
                    int idc = (int)hb_ue(b);
                    if (idc == 3) break;
                    if (idc > 3 || s->n_mod[l] >= 33) { h264_say(d, "a reference list change that does not end"); return -1; }
                    s->mod[l][s->n_mod[l]][0] = idc;
                    s->mod[l][s->n_mod[l]][1] = (int)hb_ue(b);
                    s->n_mod[l]++;
                }
            }
        }
    }
    s->luma_denom = s->chroma_denom = 0;
    if ((pp->weighted_pred && s->type == H264_P) || (pp->weighted_bipred == 1 && s->type == H264_B)) {
        h264_weights(d, b);
        if (!s->luma_denom && !s->chroma_denom && hb_over(b)) { h264_say(d, "a weight table that stops short"); return -1; }
    }
    s->no_output_prior = s->long_term_ref = s->adaptive_marking = 0;
    s->n_mmco = 0;
    if (nal_ref_idc) {
        if (s->idr) {
            s->no_output_prior = hb_bit(b);
            s->long_term_ref = hb_bit(b);
        } else {
            s->adaptive_marking = hb_bit(b);
            if (s->adaptive_marking) {
                for (;;) {
                    int op = (int)hb_ue(b);
                    if (op == 0) break;
                    if (op > 6 || s->n_mmco >= 72) { h264_say(d, "memory management that does not end"); return -1; }
                    int a = 0, c = 0;
                    if (op == 1 || op == 3) a = (int)hb_ue(b);
                    if (op == 2) a = (int)hb_ue(b);
                    if (op == 3 || op == 6) c = (int)hb_ue(b);
                    if (op == 4) a = (int)hb_ue(b);
                    s->mmco[s->n_mmco][0] = op;
                    s->mmco[s->n_mmco][1] = a;
                    s->mmco[s->n_mmco][2] = c;
                    s->n_mmco++;
                }
            }
        }
    }
    s->cabac_init_idc = (pp->cabac && s->type != H264_I) ? (int)hb_ue(b) : 0;
    if (s->cabac_init_idc > 2) { h264_say(d, "a CABAC table that does not exist"); return -1; }
    s->qp = pp->init_qp + hb_se(b);
    if (s->qp < 0 || s->qp > 51) { h264_say(d, "a quantiser out of range"); return -1; }
    s->deblock_idc = 0;
    s->alpha_off = s->beta_off = 0;
    if (pp->deblock_control) {
        s->deblock_idc = (int)hb_ue(b);
        if (s->deblock_idc != 1) { s->alpha_off = hb_se(b) * 2; s->beta_off = hb_se(b) * 2; }
        if (s->deblock_idc > 2 || s->alpha_off < -12 || s->alpha_off > 12 || s->beta_off < -12 || s->beta_off > 12) {
            h264_say(d, "deblocking settings out of range");
            return -1;
        }
    }
    if (hb_over(b)) { h264_say(d, "a slice header that stops short"); return -1; }
    return 0;
}

/* --- picture order (8.2.1) ----------------------------------------------------------------- */

static int h264_poc(h264_dec *d) {
    const h264_sps *sp = d->sp;
    h264_slice *s = &d->sl;
    if (sp->poc_type == 0) {
        if (s->idr) { d->prev_poc_msb = 0; d->prev_poc_lsb = 0; }
        else if (d->prev_mmco5) { d->prev_poc_msb = 0; d->prev_poc_lsb = d->prev_ref_poc_after_mmco5; }
        int max = 1 << sp->log2_max_poc_lsb, msb;
        if (s->poc_lsb < d->prev_poc_lsb && d->prev_poc_lsb - s->poc_lsb >= max / 2) msb = d->prev_poc_msb + max;
        else if (s->poc_lsb > d->prev_poc_lsb && s->poc_lsb - d->prev_poc_lsb > max / 2) msb = d->prev_poc_msb - max;
        else msb = d->prev_poc_msb;
        int top = msb + s->poc_lsb, bottom = top + s->delta_poc_bottom;
        if (s->nal_ref_idc) { d->prev_poc_msb = msb; d->prev_poc_lsb = s->poc_lsb; }
        return top < bottom ? top : bottom;
    }
    int offset;
    if (s->idr) offset = 0;
    else if (d->prev_mmco5) offset = 0;
    else if (d->prev_frame_num > s->frame_num) offset = d->prev_frame_num_offset + d->max_frame_num;
    else offset = d->prev_frame_num_offset;
    d->prev_frame_num_offset = offset;
    if (sp->poc_type == 1) {
        int abs_num = sp->poc_cycle ? offset + s->frame_num : 0;
        if (!s->nal_ref_idc && abs_num > 0) abs_num--;
        int expected = 0;
        if (abs_num > 0) {
            int per_cycle = 0;
            for (int i = 0; i < sp->poc_cycle; i++) per_cycle += sp->offset_for_ref_frame[i];
            int cycle = (abs_num - 1) / sp->poc_cycle, in = (abs_num - 1) % sp->poc_cycle;
            expected = cycle * per_cycle;
            for (int i = 0; i <= in; i++) expected += sp->offset_for_ref_frame[i];
        }
        if (!s->nal_ref_idc) expected += sp->offset_for_non_ref_pic;
        int top = expected + s->delta_poc[0];
        int bottom = top + sp->offset_for_top_to_bottom_field + s->delta_poc[1];
        return top < bottom ? top : bottom;
    }
    if (s->idr) return 0;
    return s->nal_ref_idc ? 2 * (offset + s->frame_num) : 2 * (offset + s->frame_num) - 1;
}

/* --- references (8.2.4, 8.2.5) ------------------------------------------------------------- */

static void h264_frame_num_wrap(h264_dec *d) {
    for (int i = 0; i < H264_DPB; i++) {
        h264_pic *p = &d->dpb[i];
        if (p->ref == 1) p->frame_num_wrap = p->frame_num > d->sl.frame_num ? p->frame_num - d->max_frame_num : p->frame_num;
    }
}

static void h264_sort(h264_pic **a, int n, int (*before)(const h264_pic *, const h264_pic *)) {
    for (int i = 1; i < n; i++) {
        h264_pic *x = a[i];
        int j = i - 1;
        while (j >= 0 && before(x, a[j])) { a[j + 1] = a[j]; j--; }
        a[j + 1] = x;
    }
}
static int h264_by_num_desc(const h264_pic *a, const h264_pic *b) { return a->frame_num_wrap > b->frame_num_wrap; }
static int h264_by_lt_asc(const h264_pic *a, const h264_pic *b) { return a->lt_idx < b->lt_idx; }
static int h264_by_poc_desc(const h264_pic *a, const h264_pic *b) { return a->poc > b->poc; }
static int h264_by_poc_asc(const h264_pic *a, const h264_pic *b) { return a->poc < b->poc; }

static int h264_init_lists(h264_dec *d) {
    h264_slice *s = &d->sl;
    h264_pic *st[H264_DPB], *lt[H264_DPB], *before[H264_DPB], *after[H264_DPB];
    int nst = 0, nlt = 0, nb = 0, na = 0;
    h264_frame_num_wrap(d);
    for (int i = 0; i < H264_DPB; i++) {
        h264_pic *p = &d->dpb[i];
        if (p == d->cur) continue;
        if (p->ref == 1) st[nst++] = p;
        else if (p->ref == 2) lt[nlt++] = p;
    }
    h264_sort(lt, nlt, h264_by_lt_asc);
    int n[2] = { 0, 0 };
    h264_pic *init[2][H264_DPB * 2];
    if (s->type == H264_P) {
        h264_sort(st, nst, h264_by_num_desc);
        for (int i = 0; i < nst; i++) init[0][n[0]++] = st[i];
        for (int i = 0; i < nlt; i++) init[0][n[0]++] = lt[i];
    } else if (s->type == H264_B) {
        for (int i = 0; i < nst; i++) {
            if (st[i]->nonexisting) continue;
            if (st[i]->poc < d->cur->poc) before[nb++] = st[i]; else after[na++] = st[i];
        }
        h264_sort(before, nb, h264_by_poc_desc);
        h264_sort(after, na, h264_by_poc_asc);
        for (int i = 0; i < nb; i++) init[0][n[0]++] = before[i];
        for (int i = 0; i < na; i++) init[0][n[0]++] = after[i];
        for (int i = 0; i < nlt; i++) init[0][n[0]++] = lt[i];
        for (int i = 0; i < na; i++) init[1][n[1]++] = after[i];
        for (int i = 0; i < nb; i++) init[1][n[1]++] = before[i];
        for (int i = 0; i < nlt; i++) init[1][n[1]++] = lt[i];
        if (n[1] > 1 && n[0] == n[1]) {
            int same = 1;
            for (int i = 0; i < n[0]; i++) if (init[0][i] != init[1][i]) same = 0;
            if (same) { h264_pic *x = init[1][0]; init[1][0] = init[1][1]; init[1][1] = x; }
        }
    }
    for (int l = 0; l < 2; l++) {
        for (int i = 0; i <= H264_MAX_LIST; i++) s->list[l][i] = i < n[l] && i < H264_MAX_LIST ? init[l][i] : 0;
        /* 8.2.4.3: the changes, in order. */
        int pred = d->sl.frame_num, idx = 0;
        for (int k = 0; k < s->n_mod[l]; k++) {
            int idc = s->mod[l][k][0], v = s->mod[l][k][1];
            if (idx >= s->num_ref[l]) { h264_say(d, "more reference list changes than references"); return -1; }
            h264_pic *pick = 0;
            if (idc < 2) {
                int max = d->max_frame_num;
                int abs_diff = v + 1;
                int no_wrap = idc == 0 ? pred - abs_diff : pred + abs_diff;
                if (no_wrap < 0) no_wrap += max;
                if (no_wrap >= max) no_wrap -= max;
                pred = no_wrap;
                int num = no_wrap > d->sl.frame_num ? no_wrap - max : no_wrap;
                for (int i = 0; i < H264_DPB; i++)
                    if (d->dpb[i].ref == 1 && &d->dpb[i] != d->cur && d->dpb[i].frame_num_wrap == num) pick = &d->dpb[i];
                if (!pick) { h264_say(d, "a reference list names a picture that is not there"); return -1; }
                for (int i = s->num_ref[l]; i > idx; i--) s->list[l][i] = s->list[l][i - 1];
                s->list[l][idx++] = pick;
                int to = idx;
                for (int i = idx; i <= s->num_ref[l]; i++) {
                    h264_pic *q = s->list[l][i];
                    if (q && !(q->ref == 1 && q->frame_num_wrap == num)) s->list[l][to++] = q;
                    else if (!q) s->list[l][to++] = q;
                }
            } else {
                for (int i = 0; i < H264_DPB; i++)
                    if (d->dpb[i].ref == 2 && d->dpb[i].lt_idx == v) pick = &d->dpb[i];
                if (!pick) { h264_say(d, "a reference list names a long-term picture that is not there"); return -1; }
                for (int i = s->num_ref[l]; i > idx; i--) s->list[l][i] = s->list[l][i - 1];
                s->list[l][idx++] = pick;
                int to = idx;
                for (int i = idx; i <= s->num_ref[l]; i++) {
                    h264_pic *q = s->list[l][i];
                    if (!(q && q->ref == 2 && q->lt_idx == v)) s->list[l][to++] = q;
                }
            }
        }
        for (int i = s->num_ref[l]; i <= H264_MAX_LIST; i++) s->list[l][i] = 0;
        /* A list shorter than it says repeats nothing: an index past the
           pictures there are is a broken stream, and is caught where a
           reference is read. */
    }
    return 0;
}

/* 8.4.2.3.1: implicit weights, w1 for each pair of references. */
static void h264_implicit(h264_dec *d) {
    h264_slice *s = &d->sl;
    for (int i = 0; i < s->num_ref[0]; i++) {
        for (int j = 0; j < s->num_ref[1]; j++) {
            h264_pic *a = s->list[0][i], *c = s->list[1][j];
            int w1 = 32;
            if (a && c && a->ref != 2 && c->ref != 2) {
                int tb = h264_clip3(-128, 127, d->cur->poc - a->poc);
                int td = h264_clip3(-128, 127, c->poc - a->poc);
                if (td) {
                    int tx = (16384 + h264_abs(td / 2)) / td;
                    int dsf = h264_clip3(-1024, 1023, (tb * tx + 32) >> 6);
                    if (!(dsf >> 2 < -64 || dsf >> 2 > 128)) w1 = dsf >> 2;
                }
            }
            s->implicit[i][j] = (short)w1;
        }
    }
}

static void h264_sliding_window(h264_dec *d) {
    int n = 0;
    for (int i = 0; i < H264_DPB; i++) if (d->dpb[i].ref && &d->dpb[i] != d->cur) n++;
    int max = d->sp->max_num_ref_frames > 0 ? d->sp->max_num_ref_frames : 1;
    while (n >= max) {
        h264_pic *old = 0;
        for (int i = 0; i < H264_DPB; i++) {
            h264_pic *p = &d->dpb[i];
            if (p->ref == 1 && p != d->cur && (!old || p->frame_num_wrap < old->frame_num_wrap)) old = p;
        }
        if (!old) break;
        old->ref = 0;
        n--;
    }
}

/* 8.2.5: after the picture, what is kept for reference. */
static void h264_mark(h264_dec *d) {
    h264_slice *s = &d->sl;
    h264_pic *cur = d->cur;
    d->prev_mmco5 = 0;
    if (!s->nal_ref_idc) return;
    if (s->idr) {
        for (int i = 0; i < H264_DPB; i++) if (&d->dpb[i] != cur) d->dpb[i].ref = 0;
        if (s->long_term_ref) { cur->ref = 2; cur->lt_idx = 0; d->max_lt_idx = 0; }
        else { cur->ref = 1; d->max_lt_idx = -1; }
        return;
    }
    int current_long = 0;
    h264_frame_num_wrap(d);
    if (s->adaptive_marking) {
        for (int k = 0; k < s->n_mmco; k++) {
            int op = s->mmco[k][0], a = s->mmco[k][1], c = s->mmco[k][2];
            if (op == 1 || op == 3) {
                int num = s->frame_num - (a + 1);
                for (int i = 0; i < H264_DPB; i++) {
                    h264_pic *p = &d->dpb[i];
                    if (p->ref == 1 && p != cur && p->frame_num_wrap == num) {
                        if (op == 1) p->ref = 0;
                        else {
                            for (int j = 0; j < H264_DPB; j++)
                                if (d->dpb[j].ref == 2 && d->dpb[j].lt_idx == c) d->dpb[j].ref = 0;
                            p->ref = 2;
                            p->lt_idx = c;
                        }
                    }
                }
            } else if (op == 2) {
                for (int i = 0; i < H264_DPB; i++)
                    if (d->dpb[i].ref == 2 && d->dpb[i].lt_idx == a) d->dpb[i].ref = 0;
            } else if (op == 4) {
                d->max_lt_idx = a - 1;
                for (int i = 0; i < H264_DPB; i++)
                    if (d->dpb[i].ref == 2 && d->dpb[i].lt_idx > d->max_lt_idx) d->dpb[i].ref = 0;
            } else if (op == 5) {
                for (int i = 0; i < H264_DPB; i++) if (&d->dpb[i] != cur) d->dpb[i].ref = 0;
                d->max_lt_idx = -1;
                d->prev_mmco5 = 1;
            } else if (op == 6) {
                for (int j = 0; j < H264_DPB; j++)
                    if (d->dpb[j].ref == 2 && d->dpb[j].lt_idx == c && &d->dpb[j] != cur) d->dpb[j].ref = 0;
                cur->ref = 2;
                cur->lt_idx = c;
                current_long = 1;
            }
        }
    } else {
        h264_sliding_window(d);
    }
    if (!current_long) cur->ref = 1;
    if (d->prev_mmco5) {
        /* The picture is now the first of a new count: its order is what it
           was less itself, and its frame number 0 (8.2.1). */
        int poc = cur->poc;
        cur->poc = 0;
        d->prev_ref_poc_after_mmco5 = 0;
        (void)poc;
        cur->frame_num = 0;
        cur->idr_like = 1;
        cur->epoch = ++d->epoch;
    }
}

/* --- output (C.4) ---------------------------------------------------------------------------- */

/* Display order: picture order within a run, and an earlier run (before an
   IDR or a reset of the count) first. */
static h264_pic *h264_next_out(h264_dec *d) {
    h264_pic *best = 0;
    for (int i = 0; i < H264_DPB; i++) {
        h264_pic *p = &d->dpb[i];
        if (p->wait_output && (!best || p->epoch < best->epoch || (p->epoch == best->epoch && p->poc < best->poc)))
            best = p;
    }
    return best;
}

static int h264_waiting(h264_dec *d) {
    int n = 0;
    for (int i = 0; i < H264_DPB; i++) if (d->dpb[i].wait_output) n++;
    return n;
}

static void h264_release(h264_dec *d) {
    for (int i = 0; i < H264_DPB; i++) {
        h264_pic *p = &d->dpb[i];
        if (p->in_use && !p->ref && !p->wait_output && p != d->cur && p != d->shown) p->in_use = 0;
    }
}

/* A free frame for the next picture; one may have to be shown first. */
static h264_pic *h264_free_frame(h264_dec *d) {
    h264_release(d);
    for (int i = 0; i < d->npics; i++) if (!d->dpb[i].in_use) return &d->dpb[i];
    return 0;
}

/* Which frames are due: more waiting than the stream reorders, or the
   buffer full. */
static int h264_due(h264_dec *d) {
    int waiting = h264_waiting(d);
    if (!waiting) return 0;
    if (d->flushing) return 1;
    for (int i = 0; i < H264_DPB; i++)
        if (d->dpb[i].wait_output && d->dpb[i].epoch < d->epoch) return 1;
    int reorder = d->sp && d->sp->num_reorder >= 0 ? d->sp->num_reorder : d->dpb_size;
    if (waiting > reorder) return 1;
    int used = 0;
    for (int i = 0; i < H264_DPB; i++) if (d->dpb[i].ref || d->dpb[i].wait_output) used++;
    return used > d->dpb_size;
}

#include "h264rec.h"
#include "h264mb.h"

/* --- the picture around the slices ------------------------------------------------------- */

static void h264_finish_picture(h264_dec *d) {
    if (!d->cur) return;
    h264_deblock_picture(d);
    h264_mark(d);
    d->cur->wait_output = 1;
    d->prev_frame_num = d->sl.frame_num;
    if (d->sl.nal_ref_idc) d->prev_ref_frame_num = d->cur->frame_num;
    d->frames_decoded++;
    d->cur = 0;
}

/* frame_num jumped: the frames in between are made up so the sliding
   window counts right (8.2.5.2). */
static void h264_gaps(h264_dec *d) {
    int num = d->sl.frame_num, prev = d->prev_ref_frame_num;
    if (d->sl.idr || num == prev || num == (prev + 1) % d->max_frame_num) return;
    int guard = 0;
    for (int f = (prev + 1) % d->max_frame_num; f != num && guard < 16; f = (f + 1) % d->max_frame_num, guard++) {
        h264_pic *p = h264_free_frame(d);
        if (!p) return;
        p->in_use = 1;
        p->nonexisting = 1;
        p->frame_num = f;
        p->wait_output = 0;
        p->poc = 0;
        p->id = ++d->next_id;
        h264_slice keep_type;                  /* the sliding window reads frame_num through sl */
        (void)keep_type;
        int real = d->sl.frame_num;
        d->sl.frame_num = f;
        h264_pic *was = d->cur;
        d->cur = p;
        h264_frame_num_wrap(d);
        h264_sliding_window(d);
        p->ref = 1;
        d->cur = was;
        d->sl.frame_num = real;
        d->prev_ref_frame_num = f;
    }
}

static int h264_start_picture(h264_dec *d) {
    const h264_pps *pp = &d->pps[d->sl.pps_id];
    if (h264_activate(d, pp) < 0) return -1;
    if (d->sl.idr) {
        for (int i = 0; i < H264_DPB; i++) d->dpb[i].ref = 0;
        if (d->sl.no_output_prior) for (int i = 0; i < H264_DPB; i++) d->dpb[i].wait_output = 0;
        d->prev_ref_frame_num = 0;
        d->epoch++;
    } else {
        h264_gaps(d);
    }
    h264_pic *p = h264_free_frame(d);
    if (!p) { h264_say(d, "no free frame: more pictures kept than the stream said it would"); return -1; }
    p->in_use = 1;
    p->nonexisting = 0;
    p->ref = 0;
    p->wait_output = 0;
    p->idr_like = d->sl.idr;
    p->frame_num = d->sl.frame_num;
    p->id = ++d->next_id;
    p->lt_idx = 0;
    p->epoch = d->epoch;
    p->pts = d->next_pts;
    d->cur = p;
    p->poc = h264_poc(d);
    for (int i = 0; i < d->mbs; i++) d->mb_slice[i] = -1;
    d->slices = 0;
    return 0;
}

static int h264_slice_data(h264_dec *d, h264_bits *b);

static int h264_slice_nal(h264_dec *d, h264_bits *b, int nal_type, int nal_ref_idc) {
    /* Whether this slice begins a new picture is in its header (7.4.1.2.4);
       the header is read into a copy first so the old picture's state is
       still there to finish it with. */
    static h264_slice keep;
    for (int i = 0; i < (int)sizeof(keep); i++) ((volatile u8 *)&keep)[i] = ((u8 *)&d->sl)[i];
    if (h264_slice_header(d, b, nal_type, nal_ref_idc) < 0) return -1;
    if (d->sl.redundant_pic_cnt > 0) return 0;     /* the primary picture is enough */
    int newpic = !d->cur || d->sl.first_mb == 0 || d->sl.frame_num != keep.frame_num ||
                 d->sl.pps_id != keep.pps_id || (d->sl.nal_ref_idc != 0) != (keep.nal_ref_idc != 0) ||
                 d->sl.idr != keep.idr || (d->sl.idr && d->sl.idr_pic_id != keep.idr_pic_id) ||
                 d->sl.poc_lsb != keep.poc_lsb || d->sl.delta_poc_bottom != keep.delta_poc_bottom;
    if (newpic && d->cur) {
        /* Finish the last picture with the header it was decoded under. */
        static h264_slice now;
        for (int i = 0; i < (int)sizeof(now); i++) ((volatile u8 *)&now)[i] = ((u8 *)&d->sl)[i];
        for (int i = 0; i < (int)sizeof(keep); i++) ((volatile u8 *)&d->sl)[i] = ((u8 *)&keep)[i];
        h264_finish_picture(d);
        for (int i = 0; i < (int)sizeof(now); i++) ((volatile u8 *)&d->sl)[i] = ((u8 *)&now)[i];
    }
    if (newpic && h264_start_picture(d) < 0) return -1;
    if (d->pps[d->sl.pps_id].sps_id != d->pp->sps_id) { h264_say(d, "a slice changes sequence mid-picture"); return -1; }
    d->pp = &d->pps[d->sl.pps_id];
    d->sl.number = d->slices++;
    if (d->sl.type != H264_I && h264_init_lists(d) < 0) return -1;
    for (int l = 0; l < 2; l++)
        for (int i = 0; i < d->sl.num_ref[l]; i++)
            if (!d->sl.list[l][i]) {
                /* A missing reference: use any there is rather than stop
                   (a stream joined part way has them; the picture will be
                   wrong until the next IDR, not the decoder). */
                for (int k = 0; k < H264_DPB && !d->sl.list[l][i]; k++)
                    if (d->dpb[k].in_use && &d->dpb[k] != d->cur && !d->dpb[k].nonexisting) d->sl.list[l][i] = &d->dpb[k];
                if (!d->sl.list[l][i]) d->sl.list[l][i] = d->cur;
            }
    if (d->sl.type == H264_B && d->pp->weighted_bipred == 2) h264_implicit(d);
    {
        const h264_slice *s = &d->sl;
        d->seen |= d->pp->cabac ? H264_SEEN_CABAC : H264_SEEN_CAVLC;
        if (s->type == H264_B) d->seen |= H264_SEEN_B | (s->direct_spatial ? H264_SEEN_SPATIAL : H264_SEEN_TEMPORAL);
        if ((s->type == H264_P && d->pp->weighted_pred) || (s->type == H264_B && d->pp->weighted_bipred == 1)) {
            for (int l = 0; l < 2; l++)
                for (int i = 0; i < s->num_ref[l]; i++)
                    if (s->lwflag[l][i] || s->cwflag[l][i]) d->seen |= H264_SEEN_EXPLICIT;
        }
        if (s->type == H264_B && d->pp->weighted_bipred == 2) d->seen |= H264_SEEN_IMPLICIT;
        if (s->num_ref[0] > 1 || s->num_ref[1] > 1) d->seen |= H264_SEEN_MULTIREF;
        if (s->n_mmco || s->long_term_ref) d->seen |= H264_SEEN_MMCO;
        for (int l = 0; l < 2; l++)
            for (int i = 0; i < s->num_ref[l]; i++)
                if (s->list[l][i] && s->list[l][i]->ref == 2) d->seen |= H264_SEEN_LONGTERM;
        if (d->pp->scaling_present || d->sp->scaling_present) d->seen |= H264_SEEN_SCALING;
        if (s->number > 0) d->seen |= H264_SEEN_SLICES;
    }
    return h264_slice_data(d, b);
}

/* --- NAL units ------------------------------------------------------------------------------- */

/* One NAL unit, without its start code. */
static int h264_nal(h264_dec *d, const u8 *p, int n) {
    if (n < 1) return 0;
    int type = p[0] & 31, ref_idc = (p[0] >> 5) & 3;
    if (type != 1 && type != 5 && type != 7 && type != 8) {
        if (type == 11 || type == 10) { /* end of stream or sequence: nothing to keep */ }
        if (type == 2 || type == 3 || type == 4) { h264_say(d, "data partitioning, which this does not decode"); return -1; }
        return 0;
    }
    if (d->rbsp_cap < n) {
        if (d->rbsp) h264_free(d->rbsp);
        d->rbsp_cap = n + 1024;
        d->rbsp = (u8 *)h264_alloc((u64)d->rbsp_cap);
        if (!d->rbsp) { d->rbsp_cap = 0; h264_say(d, "not enough memory for a NAL unit"); return -1; }
    }
    int m = 0, zeros = 0;
    for (int i = 1; i < n; i++) {
        if (zeros >= 2 && p[i] == 3) { zeros = 0; continue; }
        zeros = p[i] ? 0 : zeros + 1;
        d->rbsp[m++] = p[i];
    }
    h264_bits b = { d->rbsp, m, 0 };
    if (type == 7) return h264_parse_sps(d, &b);
    if (type == 8) return h264_parse_pps(d, &b);
    return h264_slice_nal(d, &b, type, ref_idc);
}

/* Whether a frame is due, and its time, without taking it: a player holds
   it in the decoder until the sound reaches it. */
__attribute__((unused)) static int h264_peek(h264_dec *d, long long *pts) {
    if (!h264_due(d)) return 0;
    h264_pic *p = h264_next_out(d);
    if (!p) return 0;
    *pts = p->pts;
    return 1;
}

/* The next frame due for showing, or 0. */
static int h264_frame(h264_dec *d, h264_picture *out) {
    if (d->shown) { d->shown = 0; h264_release(d); }
    if (!h264_due(d)) return 0;
    h264_pic *p = h264_next_out(d);
    if (!p) return 0;
    p->wait_output = 0;
    d->shown = p;
    d->frames_out++;
    const h264_sps *sp = d->sp;
    int w = d->mb_w * 16;
    out->stride_y = w;
    out->stride_c = w / 2;
    out->y = p->y + sp->crop_t * w + sp->crop_l;
    out->cb = p->cb + (sp->crop_t / 2) * (w / 2) + sp->crop_l / 2;
    out->cr = p->cr + (sp->crop_t / 2) * (w / 2) + sp->crop_l / 2;
    out->width = w - sp->crop_l - sp->crop_r;
    out->height = d->mb_h * 16 - sp->crop_t - sp->crop_b;
    out->poc = p->poc;
    out->pts = p->pts;
    out->full_range = sp->full_range;
    out->matrix = sp->matrix;
    return 1;
}

/* The end of the stream: the last picture finished and everything waiting
   made due. */
static void h264_flush(h264_dec *d) {
    if (d->cur) h264_finish_picture(d);
    d->flushing = 1;
}

/* The next NAL unit of an Annex B buffer after *at: its start and length
   (trailing zero bytes left out); 0 when there are no more. */
__attribute__((unused)) static int h264_next_nal(const u8 *p, int n, int *at, int *start, int *len) {
    int i = *at;
    while (i + 3 <= n && !(p[i] == 0 && p[i + 1] == 0 && p[i + 2] == 1)) i++;
    if (i + 3 > n) { *at = n; return 0; }
    int s = i + 3, e = s;
    while (e + 3 <= n && !(p[e] == 0 && p[e + 1] == 0 && p[e + 2] == 1)) e++;
    if (e + 3 > n) e = n;
    *at = e;
    while (e > s && p[e - 1] == 0) e--;
    *start = s;
    *len = e - s;
    return 1;
}

/* How many more pictures can be decoded before a frame has to be taken.
   A caller that holds frames back (to show them on time) decodes only
   while this is above 0, and takes the frames that are due in between. */
__attribute__((unused)) static int h264_room(h264_dec *d) {
    if (!d->npics) return 1;                   /* nothing yet: the first picture makes them */
    h264_release(d);
    int n = 0;
    for (int i = 0; i < d->npics; i++) if (!d->dpb[i].in_use) n++;
    return n;
}

/* A whole access unit (a transport stream's PES packet) and its time. Its
   picture is begun while pts is the time given to it; the picture is
   finished, and becomes due for showing, when the next one begins (or at
   h264_flush). */
__attribute__((unused)) static int h264_decode_au(h264_dec *d, const u8 *p, int n, long long pts) {
    d->next_pts = pts;
    int at = 0, s, len, bad = 0;
    while (h264_next_nal(p, n, &at, &s, &len))
        if (h264_nal(d, p + s, len) < 0) bad = 1;
    return bad ? -1 : 0;
}

static void h264_open(h264_dec *d) {
    for (int i = 0; i < (int)sizeof(*d); i++) ((volatile u8 *)d)[i] = 0;
    d->max_lt_idx = -1;
}

__attribute__((unused)) static void h264_close(h264_dec *d) {
    h264_free_pics(d);
    if (d->rbsp) h264_free(d->rbsp);
    d->rbsp = 0;
}
